[project]
name = "{{ project_name }}"
version = "0.1.0"
description = "{{ project_description }}"
authors = [
    { name = "{{ author_name }}", email = "{{ author_email }}" }
]
requires-python = ">={{ minimum_python_version }}"
dependencies = [
    "jinja2>=3.1.4",
    "typer>=0.14.0",
]
